apiVersion: v2
name: lava
description: Helm chart for deploying LAVA (Linaro Automated Validation Architecture) on Kubernetes
type: application
version: 1.0.0
appVersion: "2025.06"
home: https://lavasoftware.org/
keywords:
  - lava
  - testing
  - validation
  - automation
  - ci
  - embedded
sources:
  - https://gitlab.com/lava/lava
  - https://github.com/Linaro/lava
maintainers:
  - name: Linaro
    email: lava-devel@lists.lavasoftware.org
    url: https://www.linaro.org/
