apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lava.fullname" . }}-json-config
  labels:
    {{- include "lava.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.json: |
    {{- .Values.lava.jsonConfig | toJson | nindent 4 }}