apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lava.fullname" . }}-config
  labels:
    {{- include "lava.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret-key: {{ .Values.lava.secretKey | default (randAlphaNum 50) | quote }}